apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
data:
  MYSQL_DATABASE: nagp_kubernetes
  MYSQL_DATABASE_USER: root
  MYSQL_DATABASE_URL: jdbc:mysql://mysql-service:3306/nagp_kubernetes?allowPublicKeyRetrieval=true&useSSL=false