apiVersion: apps/v1
kind: Deployment
metadata:
  name: nagp-app

spec:
  replicas: 4

  selector:
    matchLabels:
      app: nagp-app

  template:
    metadata:
      labels:
        app: nagp-app

    spec:
      containers:
        - name: nagp-app
          image: gdave940/nagp-kubernetes:latest
          imagePullPolicy: Always

          ports:
            - containerPort: 8080

          env:
            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  name: mysql-config
                  key: MYSQL_DATABASE_URL

            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: mysql-config
                  key: MYSQL_DATABASE_USER

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_ROOT_PASSWORD

          resources:
            requests:
              cpu: "50m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"

