apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nagp-app-ingress
  labels:
    tier: application
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nagp-app-service
                port:
                  number: 80